/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

export default class Datagram {
    public addUint8(arg: number) {}
    public addInt8(arg: number) {}
    public addUint16(arg: number) {}
    public addInt16(arg: number) {}
    public addUint32(arg: number) {}
    public addInt32(arg: number) {}
}
