/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

export default class DatagramIterator {
    public getUint8(): number {
        return 0;
    }

    public getInt8(): number {
        return 0;
    }

    public getUint16(): number {
        return 0;
    }

    public getInt16(): number {
        return 0;
    }

    public getUint32(): number {
        return 0;
    }

    public getInt32(): number {
        return 0;
    }

    public getUint64(): bigint {
        return BigInt(0);
    }

    public getInt64(): bigint {
        return BigInt(0);
    }

    public getChar(): string {
        return "";
    }

    public getString(): string {
        return "";
    }

    public getUint32Array(): number[] {
        return [0];
    }

    public getRemainingSize(): number {
        return 0;
    }
}
