/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
import DatagramIterator from "./DatagramIterator";

export default class ReadHelper {
    public static readArrayStatic(di: DatagramIterator, callback: (arrayData: DatagramIterator) => any): any[] {
        const data = di.getBlob();
        const arrayData = new DatagramIterator(data);

        const array = [];
        while (arrayData.getRemainingSize()) {
            array.push(callback(arrayData));
        }

        return array;
    }
}
