/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
import DatagramIterator from "./DatagramIterator";

export default class ReadHelper {
    public static readArrayStatic(di: DatagramIterator, callback: () => any): any[] {
        const arrayLength = di.getUint16()

        const array = [];
        for (let i = 0; i < arrayLength; i++) {
            array.push(callback())
        }

        return array;
    }
}
