/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

import DatagramIterator from "./DatagramIterator";
import Datagram from "./Datagram";

export default class ReadHelper {
    public static readArrayStatic(di: DatagramIterator, callback: (arrayData: DatagramIterator) => any): any[] {
        const data = di.getBlob();
        const arrayData = new DatagramIterator(data);

        const array = [];
        while (arrayData.getRemainingSize()) {
            array.push(callback(arrayData));
        }

        return array;
    }

    public static writeArrayStatic(dg: Datagram, arr: any[], callback: (arrData: Datagram, arrVal: any) => void): void {
        const dg2 = new Datagram();
        for (const data of arr) {
            callback(dg2, data);
        }
        dg.addBlob(dg2.getMessage());
    }
}
