/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

export default class UniqueIdAllocator {
    public static readonly IndexEnd = -1;
    public static readonly IndexAllocated = -2;

    private readonly _min: number;
    private readonly _max: number;

    private readonly _size: number;
    private _table: number[];

    private _next_free: number;
    private _last_free: number;
    private _free: number;

    /**
     * Create a free id pool in the range [min:max].
     */
    constructor(min: number, max: number) {
        if (!Number.isInteger(min) || !Number.isInteger(max)) {
            throw new Error("UniqueIdAllocator: min/max must be integers");
        }

        if (max < min) {
            throw new Error("UniqueIdAllocator: max must be >= min");
        }

        this._min = min;
        this._max = max;

        this._size = this._max - this._min + 1; // +1 because min and max are inclusive.
        if (this._size <= 0) {
            throw new Error("UniqueIdAllocator: size must be > 0");
        }

        this._table = new Array(this._size);

        for (let i = 0; i < this._size; ++i) {
            this._table[i] = i + 1;
        }
        this._table[this._size - 1] = UniqueIdAllocator.IndexEnd;

        this._next_free = 0;
        this._last_free = this._size - 1;
        this._free = this._size;
    }

    /**
     * Returns an id between _min and _max (that were passed to the constructor).
     * IndexEnd is returned if no ids are available.
     */
    allocate(): number {
        if (this._next_free === UniqueIdAllocator.IndexEnd) {
            // ...all ids allocated.
            return UniqueIdAllocator.IndexEnd;
        }

        const index = this._next_free;

        if (this._table[index] === UniqueIdAllocator.IndexAllocated) {
            // Corrupted state (should not happen)
            return UniqueIdAllocator.IndexEnd;
        }

        this._next_free = this._table[this._next_free];
        this._table[index] = UniqueIdAllocator.IndexAllocated;

        --this._free;

        const id = index + this._min;
        return id;
    }

    /**
     * This may be called to mark a particular id as having already been allocated
     * (for instance, by a prior pass).  The specified id is removed from the
     * available pool.
     *
     * Because of the limitations of this algorithm, this is most efficient when
     * it is called before the first call to allocate(), and when all the calls to
     * initialReserveId() are made in descending order by id.  However, this is
     * a performance warning only; if performance is not an issue, any id may be
     * reserved at any time.
     * @param id
     */
    initialReserveId(id: number): void {
        if (!Number.isInteger(id)) {
            throw new Error("initial_reserve_id: id must be an integer");
        }

        if (id < this._min || id > this._max) {
            // Attempt to reserve out-of-range id.
            throw new Error("initial_reserve_id: id out of range");
        }

        const index = id - this._min; // Convert to _table index.

        if (this._table[index] === UniqueIdAllocator.IndexAllocated) {
            throw new Error("initial_reserve_id: id already allocated");
        }

        if (this._free === 1) {
            // We just reserved the last element in the free chain.
            this._next_free = UniqueIdAllocator.IndexEnd;
        } else if (this._next_free === index) {
            // We're reserving the head of the free chain.
            this._next_free = this._table[index];
        } else {
            // Since we don't store back pointers in the free chain, we have to search
            // for the element in the free chain that points to this index.

            /*
             * However, there is an easy optimal case: because we expect that this call
             * will be made before any calls to allocate(), hopefully is it still true
             * that the _table is still set up such that _table[i] = i+1 (and if the
             * numbers are reserved in descending order, this will be true at least for
             * all i <= index).  Thus, the free link to slot [index] is expected to be the
             * slot right before it, or if not, it usually won't be far before it.
             */

            let prev_index = index;

            while (prev_index > 0 && this._table[prev_index - 1] !== index) {
                --prev_index;
            }

            if (prev_index > 0 && this._table[prev_index - 1] === index) {
                // We've found it.
                --prev_index;
            } else {
                // OK, it wasn't found below; we have to search above.
                prev_index = index + 1;
                while (prev_index < this._size && this._table[prev_index] !== index) {
                    ++prev_index;
                }
            }

            if (prev_index >= this._size || this._table[prev_index] !== index) {
                throw new Error("initial_reserve_id: corrupted free chain");
            }

            this._table[prev_index] = this._table[index];

            if (index === this._last_free) {
                this._last_free = prev_index;
            }
        }

        this._table[index] = UniqueIdAllocator.IndexAllocated;
        --this._free;
    }

    /**
     * Checks the allocated state of an index. Returns true for
     * indices that are currently allocated and in use.
     */
    is_allocated(id: number): boolean {
        if (!Number.isInteger(id)) {
            return false;
        }

        if (id < this._min || id > this._max) {
            // This id is out of range, not allocated.
            return false;
        }

        const index = id - this._min; // Convert to _table index.
        return this._table[index] === UniqueIdAllocator.IndexAllocated;
    }

    /**
     * Free an allocated index (index must be between _min and _max that were
     * passed to the constructor).
     */
    free(id: number): boolean {
        if (!Number.isInteger(id)) {
            return false;
        }

        if (id < this._min || id > this._max) {
            // Attempt to free out-of-range id.
            return false;
        }

        const index = id - this._min; // Convert to _table index.

        if (this._table[index] !== UniqueIdAllocator.IndexAllocated) {
            // Attempt to free non-allocated id.
            return false;
        }

        if (this._next_free !== UniqueIdAllocator.IndexEnd) {
            if (this._table[this._last_free] !== UniqueIdAllocator.IndexEnd) {
                return false; // corrupted chain
            }
            this._table[this._last_free] = index;
        }

        this._table[index] = UniqueIdAllocator.IndexEnd; // Mark this element as the end of the list.
        this._last_free = index;

        if (this._next_free === UniqueIdAllocator.IndexEnd) {
            // ...the free list was empty.
            this._next_free = index;
        }

        ++this._free;
        return true;
    }

    /**
     * return the decimal fraction of the pool that is used.  The range is 0 to
     * 1.0 (e.g.  75% would be 0.75).
     */
    fractionUsed(): number {
        return (this._size - this._free) / this._size;
    }
}
