struct_template = """/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
 
export default class {className} {{
{fields}
}}
"""

class_template = """/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
{imports}
export default interface I{className}{extends} {{
{fields}
}}
"""


class DCInterfaceTS:
    def __init__(self, name, dclass, out_path):
        self.name = name
        self.dclass = dclass
        self.outPath = out_path
        self.outName = ""
        self.outBuffer = ""

        if dclass.isStruct():
            self._gen_struct_buffer()
        else:
            self._gen_class_buffer()

    def _gen_struct_buffer(self):
        self.outName = f"{self.name}.ts"

        fields = ""
        for i in range(self.dclass.get_num_fields()):
            field = self.dclass.get_field(i)
            field_type = "number"  # TODO.
            fields += f"\tpublic {field.getName()}!: {field_type};\n"

        if fields:
            # Chop off our last char (\n)
            fields = fields[:-1]

        self.outBuffer = struct_template.format(className=self.name, fields=fields)

    def _gen_class_buffer(self):
        self.outName = f"I{self.name}.ts"

        imports = ""
        extends = ""

        if self.dclass.get_num_parents():
            # This distributed class inherits from at least one parent.
            extends = " extends "
            for i in range(self.dclass.get_num_parents()):
                parent = self.dclass.get_parent(i)
                name = f"I{parent.getName()}"  # Prepend with an 'I'
                imports += f'import {name} from "./{name}";\n'
                extends += f"{name}, "

            # Chop off our last two chars (, )
            extends = extends[:-2]

        fields = ""
        for i in range(self.dclass.get_num_fields()):
            field = self.dclass.get_field(i)
            # TODO: Field args.
            fields += f"\t{field.getName()}(): void;\n"

        if fields:
            # Chop off our last char (\n)
            fields = fields[:-1]

        self.outBuffer = class_template.format(
            className=self.name, imports=imports, extends=extends, fields=fields
        )

    def write(self):
        if not self.outName or not self.outBuffer:
            return

        with open(self.outPath / self.outName, "w") as out_file:
            out_file.write(self.outBuffer)
