template = """/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
import DCMapping from "../../otp/dc/DCMapping";

export default class Mapping implements DCMapping {{
    public getDCVersion(): number {{
        return {dcHash};
    }}
"""


class MappingTS:
    def __init__(self, dc_loader, out_path):
        self.dcLoader = dc_loader
        self.outPath = out_path
        self.outBuffer = ""

        self._gen_buffer()

    def _gen_buffer(self):
        self.outBuffer = template.format(dcHash=self.dcLoader.hash_value)
        self.outBuffer += "}"

    def write(self):
        with open(self.outPath / "Mapping.ts", "w") as out_file:
            out_file.write(self.outBuffer)
