/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
import OTPClientRepository from "./OTPClientRepository";

export default interface DCInterface {
    doId: number;
    cr?: OTPClientRepository;
    parent: number;
    zone: number;
    isOwner: boolean;
    setRemote(remote: any): void;
    generateComplete(): void;
    beforeGenerate(): void;
    afterGenerate(): void;
    beforeDelete(): void;
    afterDelete(): void;
}
