/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */
import OTPClientRepository from "./OTPClientRepository";

export default class RemoteBase {
    private readonly _doId: number;
    private readonly cr: OTPClientRepository;

    constructor(doId: number, cr: OTPClientRepository) {
        this._doId = doId;
        this.cr = cr;
    }

    public get doId(): number {
        return this._doId;
    }

    protected sendUpdate(data: any) {
        this.cr.sendDatagram(data.readyData);
    }

    protected getPacker() {
        return null;
    }
}
