/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

export default class RemoteBase {
    private readonly netManager: any;
    private readonly _doId: number;

    constructor(netManager: any, doId: number) {
        this.netManager = netManager;
        this._doId = doId;
    }

    public get doId(): number {
        return this._doId;
    }

    protected sendUpdate(data: any) {
        this.netManager.sendData(data.readyData);
    }

    protected getPacker() {
        return null;
    }
}
