/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

import DatagramIterator from "../../otp/net/DatagramIterator";
import MessageTypes from "../../otp/net/MessageTypes";
import Datagram from "../../otp/net/Datagram";
import UniqueIdAllocator from "../../otp/net/UniqueIdAllocator";
import ArdosDatabaseInterface from "./ArdosDatabaseInterface";
import NetMessenger from "./NetMessenger";
import DClasses from "../../otp/dc/dclasses";

export type AnyCallback = (...args: any[]) => unknown | Promise<unknown>;

export default class ArdosInternalRepository {
    private baseChannel: number;
    private readonly serverId: bigint;
    private dcSuffix: string;
    private channelAllocator: UniqueIdAllocator;
    public dbInterface: ArdosDatabaseInterface;
    public netMessenger: NetMessenger;
    public readonly ourChannel: bigint;
    private registeredChannels: bigint[] = [];

    private __contextCounter: number = 0;
    private __callbacks: Map<number, AnyCallback> = new Map();

    constructor(baseChannel: number, maxChannels: number, serverId: number, dcSuffix?: string) {
        this.baseChannel = baseChannel;
        this.serverId = BigInt(serverId);
        this.dcSuffix = dcSuffix ?? "AI";

        this.channelAllocator = new UniqueIdAllocator(BigInt(baseChannel), BigInt(baseChannel + maxChannels - 1));

        this.dbInterface = new ArdosDatabaseInterface(this);
        this.netMessenger = new NetMessenger(this);
        this.ourChannel = this.allocateChannel();
    }

    public isConnected(): boolean {
        /**
         * Inheritors to override.
         * Provides a fast failure path for requests if we're not connected.
         */
        return false;
    }

    public sendDatagram(dg: Datagram) {
        /**
         * Inheritors to override.
         */
    }

    protected handleConnected() {
        // Listen to our channel...
        this.registerForChannel(this.ourChannel);

        // If we're configured with a State Server, register a post-remove to
        // clean up whatever objects we own on this server should we unexpectedly
        // fall over and die.
        if (this.serverId) {
            const dg = new Datagram();
            dg.addServerHeader(this.serverId, this.ourChannel, MessageTypes.STATESERVER_DELETE_AI_OBJECTS);
            dg.addChannel(this.ourChannel);
            this.addPostRemove(dg);
        }
    }

    protected handleDisconnected() {
        // Resolve all pending DB operations with failure.
        this.dbInterface.destroy();
    }

    public getContext(): number {
        this.__contextCounter = (this.__contextCounter + 1) >>> 0;
        return this.__contextCounter;
    }

    public getPuppetConnectionChannel(doId: number): bigint {
        return BigInt(doId) + (1001n << 32n);
    }

    public getAccountConnectionChannel(doId: number): bigint {
        return BigInt(doId) + (1003n << 32n);
    }

    public getAccountIDFromChannelCode(channel: bigint): bigint {
        return channel >> 32n;
    }

    /**
     * Allocate an unused channel out of this AIR's configured channel space.
     * This is also used to allocate IDs for DistributedObjects, since those
     * occupy a channel.
     */
    public allocateChannel() {
        return this.channelAllocator.allocate();
    }

    /**
     * Return the previously-allocated channel back to the allocation pool.
     * @param channel
     */
    public deallocateChannel(channel: bigint) {
        this.channelAllocator.free(channel);
    }

    /**
     * Register for messages on a specific Message Director channel.
     * If the channel is already open by this AIR, nothing will happen.
     * @param channel
     */
    public registerForChannel(channel: bigint) {
        if (this.registeredChannels.includes(channel)) {
            return;
        }
        this.registeredChannels.push(channel);

        const dg = new Datagram();
        dg.addServerControlHeader(MessageTypes.CONTROL_ADD_CHANNEL);
        dg.addChannel(channel);
        this.sendDatagram(dg);
    }

    /**
     * Unregister a channel subscription on the Message Director. The Message
     * Director will cease to relay messages to this AIR sent on the channel.
     * @param channel
     */
    public unregisterForChannel(channel: bigint) {
        const index = this.registeredChannels.indexOf(channel);
        if (index === -1) {
            return;
        }

        this.registeredChannels.splice(index, 1);

        const dg = new Datagram();
        dg.addServerControlHeader(MessageTypes.CONTROL_REMOVE_CHANNEL);
        dg.addChannel(channel);
        this.sendDatagram(dg);
    }

    /**
     * Register a datagram with the Message Director that gets sent out if the
     * connection is ever lost.
     * This is useful for registering cleanup messages: If the Panda3D process
     * ever crashes unexpectedly, the Message Director will detect the socket
     * close and automatically process any post-remove datagrams.
     * @param dg
     */
    public addPostRemove(dg: Datagram) {
        const dg2 = new Datagram();
        dg2.addServerControlHeader(MessageTypes.CONTROL_ADD_POST_REMOVE);
        dg2.addChannel(this.ourChannel);
        dg2.addBlob(dg.getMessage());
        this.sendDatagram(dg2);
    }

    /**
     * Clear all datagrams registered with addPostRemove.
     * This is useful if the server process is performing a clean exit. It may
     * clear the "emergency clean-up" post-remove messages and perform a normal
     * exit-time clean-up instead, depending on the specific exit cause.
     */
    public clearPostRemove() {
        const dg = new Datagram();
        dg.addServerControlHeader(MessageTypes.CONTROL_CLEAR_POST_REMOVES);
        dg.addChannel(this.ourChannel);
        this.sendDatagram(dg);
    }

    /**
     * Set the connection name for this MD client displayed in Ardos logs.
     * @param name
     */
    public setConName(name: string) {
        const dg = new Datagram();
        dg.addServerControlHeader(MessageTypes.CONTROL_SET_CON_NAME);
        dg.addString(name);
        this.sendDatagram(dg);
    }

    /**
     * Kicks the client residing at the specified clientChannel, using the specified reasoning.
     * @param clientChannel
     * @param reasonCode
     * @param reason
     */
    public eject(clientChannel: bigint, reasonCode: number, reason: string) {
        const dg = new Datagram();
        dg.addServerHeader(clientChannel, this.ourChannel, MessageTypes.CLIENTAGENT_EJECT);
        dg.addUint16(reasonCode);
        dg.addString(reason);
        this.sendDatagram(dg);
    }

    /**
     * Get the endpoints of a client connection.
     * You should already be sure the client actually exists, otherwise the
     * callback will never be called.
     * Callback is called as: callback(remoteIp, remotePort, localIp, localPort)
     * @param clientId
     * @param callback
     */
    public getNetworkAddress(clientId: bigint, callback: AnyCallback) {
        const ctx = this.getContext();
        this.__callbacks.set(ctx, callback);
        const dg = new Datagram();
        dg.addServerHeader(clientId, this.ourChannel, MessageTypes.CLIENTAGENT_GET_NETWORK_ADDRESS);
        dg.addUint32(ctx);
        this.sendDatagram(dg);
    }

    public handleDatagram(di: DatagramIterator) {
        const channels = [];
        const channelCount = di.getUint8();
        for (let i = 0; i < channelCount; i++) {
            channels.push(di.getUint64());
        }

        di.setServerChannels(di.getUint64(), channels);

        const msgType = di.getUint16();
        switch (msgType) {
            case MessageTypes.STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED:
            case MessageTypes.STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED_OTHER:
                // TODO.
                throw new Error("Got unexpected AI enter.");
            case MessageTypes.STATESERVER_OBJECT_CHANGING_AI:
            case MessageTypes.STATESERVER_OBJECT_DELETE_RAM:
                // TODO.
                throw new Error("Got unexpected object leaving.");
            case MessageTypes.STATESERVER_OBJECT_CHANGING_LOCATION:
                // TODO.
                throw new Error("Got unexpected object changing location.");
            case MessageTypes.DBSERVER_CREATE_OBJECT_RESP:
            case MessageTypes.DBSERVER_OBJECT_GET_ALL_RESP:
            case MessageTypes.DBSERVER_OBJECT_GET_FIELDS_RESP:
            case MessageTypes.DBSERVER_OBJECT_GET_FIELD_RESP:
            case MessageTypes.DBSERVER_OBJECT_SET_FIELD_IF_EQUALS_RESP:
            case MessageTypes.DBSERVER_OBJECT_SET_FIELDS_IF_EQUALS_RESP:
                this.dbInterface.handleDatagram(msgType, di);
                return;
            case MessageTypes.DBSS_OBJECT_GET_ACTIVATED_RESP:
                // TODO.
                throw new Error("Got unexpected DBSS activated response.");
            case MessageTypes.STATESERVER_OBJECT_GET_LOCATION_RESP:
                // TODO.
                throw new Error("Got unexpected object get location resp.");
            case MessageTypes.STATESERVER_OBJECT_GET_ALL_RESP:
                // TODO.
                throw new Error("Got unexpected object get all resp.");
            case MessageTypes.CLIENTAGENT_GET_NETWORK_ADDRESS_RESP:
                this.handleGetNetworkAddressResp(di);
                return;
        }

        if (msgType >= 20000) {
            // These messages belong to the NetMessenger:
            this.netMessenger.handle(msgType, di);
        } else {
            console.warn(`Received message with unknown MsgType=${msgType}`);
        }
    }

    protected handleGetNetworkAddressResp(di: DatagramIterator) {
        const ctx = di.getUint32();
        const remoteIp = di.getString();
        const remotePort = di.getUint16();
        const localIp = di.getString();
        const localPort = di.getUint16();

        if (!this.__callbacks.has(ctx)) {
            console.warn(`Received unexpected CLIENTAGENT_GET_NETWORK_ADDRESS_RESP (ctx: ${ctx})`);
            return;
        }

        try {
            this.__callbacks.get(ctx)!(remoteIp, remotePort, localIp, localPort);
        } finally {
            this.__callbacks.delete(ctx);
        }
    }

    public aiFormatUpdate(
        dclassName: string,
        fieldName: string,
        doId: number,
        toId: bigint,
        fromId: bigint,
        args: any,
    ) {
        const dclass = DClasses.getByName(dclassName);
        if (!dclass) {
            console.error(`dclass ${dclassName} not found in DC files`);
            return;
        }

        const field = dclass.getFieldByName(fieldName);
        if (!field) {
            console.error(`field ${fieldName} not found in dclass ${dclassName}`);
            return;
        }

        const dg = new Datagram();
        dg.addUint8(1);
        dg.addUint64(toId);
        dg.addUint64(fromId);
        dg.addUint16(MessageTypes.STATESERVER_OBJECT_SET_FIELD);
        dg.addUint32(doId);
        dg.addUint16(field.id);
        dclass.encodeField(field.id, dg, args);
        return dg;
    }

    /**
     * Used for sending messages from an AI -> UD
     * @param dclassName
     * @param fieldName
     * @param doId
     * @param args
     */
    public sendUpdateToUD(dclassName: string, fieldName: string, doId: number, args: any) {
        const dg = this.aiFormatUpdate(dclassName, fieldName, doId, BigInt(doId), this.ourChannel, args);
        if (!dg) {
            return;
        }

        this.sendDatagram(dg);
    }

    /**
     * Used for sending messages from an UD -> AI
     * @param dclassName
     * @param fieldName
     * @param doId
     * @param channel
     * @param args
     * @param sender
     */
    public sendUpdateToAI(
        dclassName: string,
        fieldName: string,
        doId: number,
        channel: bigint,
        args: any,
        sender: bigint = 0n,
    ) {
        const dg = this.aiFormatUpdate(
            dclassName,
            fieldName,
            doId,
            channel,
            sender || this.ourChannel,
            args,
        );
        if (!dg) {
            return;
        }

        this.sendDatagram(dg);
    }
}
