/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

import type ArdosInternalRepository from "./ArdosInternalRepository";
import DatagramIterator from "../../otp/net/DatagramIterator";
import MessageTypes from "../../otp/net/MessageTypes";
import Datagram from "../../otp/net/Datagram";
import DClasses, {DCClassDescriptor} from "../../otp/dc/dclasses";

type PendingRequest<T> = {
    resolve: (value: T) => void;
    timeout: NodeJS.Timeout;
    dclass?: DCClassDescriptor;
    failValue: T;
};

export default class ArdosDatabaseInterface {
    // Default 5 seconds, configurable.
    public requestTimeoutMs = 5000;

    private readonly air: ArdosInternalRepository;
    private __pending: Map<number, PendingRequest<any>> = new Map();

    constructor(air: ArdosInternalRepository) {
        this.air = air;
    }

    private createPending<T>(ctx: number, failValue: T, dclass?: DCClassDescriptor): Promise<T> {
        return new Promise<T>((resolve) => {
            const timeout = setTimeout(() => {
                const pending = this.__pending.get(ctx);
                if (!pending) return;

                console.warn(`Database operation (${ctx}) timed out.`);

                // Timeout = resolve "failure" value.
                // Each handler decides what failure means.
                this.__pending.delete(ctx);
                resolve(pending.failValue);
            }, this.requestTimeoutMs);

            this.__pending.set(ctx, {resolve, timeout, dclass, failValue});
        });
    }

    private resolvePending<T>(ctx: number, value: T): boolean {
        const pending = this.__pending.get(ctx);
        if (!pending) return false;

        clearTimeout(pending.timeout);
        this.__pending.delete(ctx);

        pending.resolve(value);
        return true;
    }

    private failPending(ctx: number): void {
        const pending = this.__pending.get(ctx);
        if (!pending) return;

        clearTimeout(pending.timeout);
        this.__pending.delete(ctx);

        pending.resolve(pending.failValue);
    }

    /**
     * Clears all pending requests, resolving them as failures.
     * Called when the TCP connection drops or the repository is shutting down.
     */
    public destroy(): void {
        for (const [ctx] of this.__pending) {
            this.failPending(ctx);
        }
        this.__pending.clear();
    }

    /**
     * Create an object in the specified database.
     *
     * databaseId specifies the control channel of the target database.
     * dclass specifies the class of the object to be created.
     * fields is a dict with any fields that should be stored in the object on creation.
     * callback will be called with callback(doId) if specified. On failure, doId is 0.
     * @param databaseId
     * @param dclass
     * @param fields
     */
    public async createObject(
        databaseId: bigint,
        dclass: DCClassDescriptor,
        fields?: Map<string, any>,
    ): Promise<number> {
        if (!this.air.isConnected()) {
            return 0;
        }

        // Save the callback.
        const ctx = this.air.getContext();
        const promise = this.createPending<number>(ctx, 0);

        try {
            // Pack up/count valid fields.
            const fieldsDg = new Datagram();
            let fieldCount = 0;
            // It's possible to create objects with default values.
            if (fields) {
                for (const [k, v] of fields) {
                    const field = dclass.getFieldByName(k);
                    if (!field) {
                        console.error(
                            `Creation request for ${dclass.CLASS_NAME} object contains invalid field named ${k}`,
                        );
                        this.failPending(ctx);
                        return promise;
                    }

                    fieldsDg.addUint16(field.id);
                    dclass.encodeField(field.id, fieldsDg, v);
                    fieldCount += 1;
                }
            }

            // Now generate and send the datagram:
            const dg = new Datagram();
            dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_CREATE_OBJECT);
            dg.addUint32(ctx);
            dg.addUint16(dclass.CLASS_ID);
            dg.addUint16(fieldCount);
            if (fieldCount) {
                dg.appendData(fieldsDg.getMessage());
            }

            this.air.sendDatagram(dg);
            return promise;
        } catch (err) {
            console.error("createObject() failed:", err);
            this.failPending(ctx);
            return promise;
        }
    }

    protected handleCreateObjectResp(di: DatagramIterator) {
        const ctx = di.getUint32();
        const doId = di.getUint32();

        if (!this.resolvePending(ctx, doId)) {
            console.warn(`Received unexpected DBSERVER_CREATE_OBJECT_RESP (ctx ${ctx}, doId ${doId})`);
        }
    }

    /**
     * Query object `doId` out of the database.
     *
     * On success, the callback will be invoked as callback(dclass, fields)
     * where dclass is a DCClass instance and fields is a dict.
     * On failure, the callback will be invoked as callback(None, None).
     * @param databaseId
     * @param doId
     * @param dclass
     * @param fieldNames
     */
    public async queryObject(
        databaseId: bigint,
        doId: number,
        dclass?: DCClassDescriptor,
        fieldNames?: string[],
    ): Promise<{dclass: DCClassDescriptor | null; fields: Map<string, any[]> | null}> {
        if (!this.air.isConnected()) {
            return {dclass: null, fields: null};
        }

        // Save the callback.
        const ctx = this.air.getContext();
        const promise = this.createPending<{
            dclass: DCClassDescriptor | null;
            fields: Map<string, any[]> | null;
        }>(ctx, {dclass: null, fields: null}, dclass);

        try {
            // Generate and send the datagram:
            const dg = new Datagram();

            if (!fieldNames) {
                dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_OBJECT_GET_ALL);
            } else {
                // We need a dclass in order to convert the field names into field IDs:
                if (!fieldNames) {
                    console.error("Missing dclass arg when providing field names.");
                    this.failPending(ctx);
                    return promise;
                }

                if (fieldNames.length > 1) {
                    dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_OBJECT_GET_FIELDS);
                } else {
                    dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_OBJECT_GET_FIELD);
                }
            }

            dg.addUint32(ctx);
            dg.addUint32(doId);
            if (fieldNames && dclass) {
                if (fieldNames.length > 1) {
                    dg.addUint16(fieldNames.length);
                }
                for (const fieldName of fieldNames) {
                    const field = dclass.getFieldByName(fieldName);
                    if (!field) {
                        console.error(`Bad field named ${fieldName} in query for ${dclass.CLASS_NAME} object`);
                        this.failPending(ctx);
                        return promise;
                    }
                    dg.addUint16(field.id);
                }
            }

            this.air.sendDatagram(dg);
            return promise;
        } catch (err) {
            console.error("queryObject() failed:", err);
            this.failPending(ctx);
            return promise;
        }
    }

    protected handleQueryObjectResp(msgType: MessageTypes, di: DatagramIterator) {
        const ctx = di.getUint32();
        const success = di.getUint8();

        const pending = this.__pending.get(ctx);
        if (!pending) {
            console.warn(`Received unexpected ${msgType} (ctx ${ctx})`);
            return;
        }

        try {
            if (!success) {
                this.failPending(ctx);
                return;
            }

            let dclassId = -1;
            let dclass: DCClassDescriptor | undefined;
            if (msgType == MessageTypes.DBSERVER_OBJECT_GET_ALL_RESP) {
                dclassId = di.getUint16();
                dclass = DClasses.getById(dclassId);
            } else {
                dclass = pending.dclass;
            }

            if (!dclass) {
                console.error(`Received bad dclass ${dclassId} in DBSERVER_OBJECT_GET_ALL_RESP`);
                this.failPending(ctx);
                return;
            }

            let fieldCount = 1;
            if (msgType !== MessageTypes.DBSERVER_OBJECT_GET_FIELD_RESP) {
                fieldCount = di.getUint16();
            }

            const fields: Map<string, any[]> = new Map();
            for (let i = 0; i < fieldCount; i++) {
                const fieldId = di.getInt16();
                const field = dclass.getFieldById(fieldId);

                if (!field) {
                    console.error(`Received bad field ${fieldId} in query for ${dclass.CLASS_NAME} object`);
                    this.failPending(ctx);
                    return;
                }

                fields.set(field.name, dclass.decodeField(fieldId, di));
            }

            this.resolvePending(ctx, {dclass, fields});
        } catch (err) {
            console.error("handleQueryObjectResp() failed:", err);
            this.failPending(ctx);
        }
    }

    /**
     * Update field(s) on an object, optionally with the requirement that the
     * fields must match some old value.
     *
     * databaseId and doId represent the database control channel and object ID
     * for the update request.
     * newFields is to be a dict of fieldname->value, representing the fields
     * to add/change on the database object.
     * oldFields, if specified, is a similarly-formatted dict that contains the
     * expected older values. If the values do not match, the database will
     * refuse to process the update. This is useful for guarding against race
     * conditions.
     *
     * On success, the callback is called as callback(None).
     * On failure, the callback is called as callback(dict), where dict contains
     * the current object values. This is so that the updater can try again,
     * basing its updates off of the new values.
     * @param databaseId
     * @param doId
     * @param dclass
     * @param newFields
     * @param oldFields
     */
    public async updateObject(
        databaseId: bigint,
        doId: number,
        dclass: DCClassDescriptor,
        newFields: Map<string, any>,
        oldFields?: Map<string, any>,
    ): Promise<null | Map<string, any[]>> {
        if (!this.air.isConnected()) {
            return new Map();
        }

        // Ensure that the keys in newFields and oldFields are the same if
        // oldFields is given...
        if (oldFields) {
            const newKeys = Object.keys(newFields);
            const oldKeys = Object.keys(oldFields);

            const sameKeys = newKeys.length === oldKeys.length && newKeys.every((k) => k in oldFields);

            if (!sameKeys) {
                console.error("newFields and oldFields must contain the same keys!");
                return new Map();
            }
        }

        try {
            const fieldsDg = new Datagram();
            let fieldCount = 0;
            for (const [k, v] of newFields) {
                const field = dclass.getFieldByName(k);
                if (!field) {
                    console.error(`Update for ${dclass.CLASS_NAME}(${doId}) object contains invalid field named ${k}`);
                    return new Map();
                }

                fieldsDg.addUint16(field.id);

                if (oldFields) {
                    // Pack the old values:
                    dclass.encodeField(field.id, fieldsDg, oldFields.get(field.name));
                }

                dclass.encodeField(field.id, fieldsDg, v);
                fieldCount += 1;
            }

            // Generate and send the datagram:
            const dg = new Datagram();
            if (oldFields) {
                const ctx = this.air.getContext();
                const promise = this.createPending<null | Map<string, any[]>>(ctx, new Map(), dclass);

                if (fieldCount == 1) {
                    dg.addServerHeader(
                        databaseId,
                        this.air.ourChannel,
                        MessageTypes.DBSERVER_OBJECT_SET_FIELD_IF_EQUALS,
                    );
                } else {
                    dg.addServerHeader(
                        databaseId,
                        this.air.ourChannel,
                        MessageTypes.DBSERVER_OBJECT_SET_FIELDS_IF_EQUALS,
                    );
                }

                dg.addUint32(ctx);
                dg.addUint32(doId);
                if (fieldCount != 1) {
                    dg.addUint16(fieldCount);
                }
                dg.appendData(fieldsDg.getMessage());
                this.air.sendDatagram(dg);
                return promise;
            }

            if (fieldCount == 1) {
                dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_OBJECT_SET_FIELD);
            } else {
                dg.addServerHeader(databaseId, this.air.ourChannel, MessageTypes.DBSERVER_OBJECT_SET_FIELDS);
            }
            dg.addUint32(doId);
            if (fieldCount != 1) {
                dg.addUint16(fieldCount);
            }
            dg.appendData(fieldsDg.getMessage());
            this.air.sendDatagram(dg);

            return null;
        } catch (err) {
            console.error("updateObject() failed:", err);
            return null;
        }
    }

    protected handleUpdateObjectResp(di: DatagramIterator, multiple: boolean) {
        const ctx = di.getUint32();
        const success = di.getUint8();

        const pending = this.__pending.get(ctx);
        if (!pending) {
            console.warn(`Received unexpected DBSERVER_OBJECT_SET_FIELD(S)_IF_EQUALS_RESP (ctx ${ctx})`);
            return;
        }

        const dclass = pending.dclass;
        if (!dclass) {
            console.warn(`Missing dclass for DBSERVER_OBJECT_SET_FIELD(S)_IF_EQUALS_RESP (ctx ${ctx})`);
            this.failPending(ctx);
            return;
        }

        try {
            if (success) {
                this.resolvePending(ctx, null);
                return;
            }

            if (!di.getRemainingSize()) {
                // We failed due to other reasons.
                this.failPending(ctx);
                return;
            }

            let fieldCount = 1;
            if (multiple) {
                fieldCount = di.getUint16();
            }

            const fields: Map<string, any[]> = new Map();
            for (let i = 0; i < fieldCount; i++) {
                const fieldId = di.getInt16();
                const field = dclass.getFieldById(fieldId);

                if (!field) {
                    console.error(`Received bad field ${fieldId} in update failure response message`);
                    this.failPending(ctx);
                    return;
                }

                fields.set(field.name, dclass.decodeField(fieldId, di));
            }

            this.resolvePending(ctx, fields);
        } catch (err) {
            console.error("handleUpdateObjectResp() failed:", err);
            this.failPending(ctx);
        }
    }

    public handleDatagram(msgType: number, di: DatagramIterator) {
        switch (msgType) {
            case MessageTypes.DBSERVER_CREATE_OBJECT_RESP:
                this.handleCreateObjectResp(di);
                return;
            case MessageTypes.DBSERVER_OBJECT_GET_ALL_RESP:
            case MessageTypes.DBSERVER_OBJECT_GET_FIELDS_RESP:
            case MessageTypes.DBSERVER_OBJECT_GET_FIELD_RESP:
                this.handleQueryObjectResp(msgType, di);
                return;
            case MessageTypes.DBSERVER_OBJECT_SET_FIELD_IF_EQUALS_RESP:
                this.handleUpdateObjectResp(di, false);
                return;
            case MessageTypes.DBSERVER_OBJECT_SET_FIELDS_IF_EQUALS_RESP:
                this.handleUpdateObjectResp(di, true);
                return;
        }
    }
}
