/**
 * THIS FILE WAS AUTOMATICALLY GENERATED BY OTP GEN
 * DO NOT MODIFY
 */

import {encode, decode} from "@msgpack/msgpack";

import type ArdosInternalRepository from "./ArdosInternalRepository";
import DatagramIterator from "../../otp/net/DatagramIterator";
import Datagram from "../../otp/net/Datagram";

type NetCallback = (...args: any[]) => void | Promise<void>;

/**
 * This works very much like the Messenger class except that messages
 * are sent over the network and (possibly) handled (accepted) on a
 * remote machine (server).
 */
export default class NetMessenger {
    private readonly air: ArdosInternalRepository;
    private readonly baseChannel: bigint;
    private readonly baseMsgType: number;

    private __message2type: Map<string, number> = new Map();
    private __type2message: Map<number, string> = new Map();
    private __message2channel: Map<string, bigint> = new Map();
    private __listeners = new Map<string, Set<NetCallback>>();

    constructor(air: ArdosInternalRepository, baseChannel: bigint = 20000n, baseMsgType: number = 20000) {
        this.air = air;
        this.baseChannel = baseChannel;
        this.baseMsgType = baseMsgType;
    }

    public register(code: number, message: string) {
        const channel = this.baseChannel + BigInt(code);
        const msgType = this.baseMsgType + code;

        if (this.__message2type.has(message)) {
            console.error(`Tried to register message ${message} twice!`);
            return;
        }

        this.__message2type.set(message, msgType);
        this.__type2message.set(msgType, message);
        this.__message2channel.set(message, channel);
    }

    public prepare(message: string, sentArgs: any[] = []): Datagram | undefined {
        if (!this.__message2type.has(message)) {
            console.error(`Tried to send unregistered message ${message}`);
            return;
        }

        const datagram = new Datagram();
        // To:
        datagram.addUint8(1);
        datagram.addChannel(this.__message2channel.get(message)!);
        // From:
        datagram.addChannel(this.air.ourChannel);

        const messageType = this.__message2type.get(message)!;
        datagram.addUint16(messageType);
        datagram.addBlob(encode(sentArgs));

        return datagram;
    }

    public accept(message: string, callback: NetCallback) {
        if (!this.__message2channel.has(message)) {
            console.error(`Tried to accept unregistered message ${message}`);
            return;
        }

        if (!this.__listeners.has(message)) {
            this.__listeners.set(message, new Set());
            // First listener, register channel with the MD.
            this.air.registerForChannel(this.__message2channel.get(message)!);
        }

        this.__listeners.get(message)!.add(callback);
    }

    public ignore(message: string, callback: NetCallback) {
        const listeners = this.__listeners.get(message);
        if (!listeners) return;

        listeners.delete(callback);
        if (listeners.size === 0) {
            this.__listeners.delete(message);
        }
    }

    public clearMessage(message: string) {
        this.__listeners.delete(message);
    }

    public clearAll() {
        this.__listeners.clear();
    }

    public send(message: string, sentArgs: any[] = []) {
        const datagram = this.prepare(message, sentArgs);
        if (!datagram) return;

        this.air.sendDatagram(datagram);

        // Also dispatch locally.
        // Shorter path than waiting for the message to echo back to us.
        void this.dispatch(message, sentArgs);
    }

    public handle(msgType: number, di: DatagramIterator) {
        /**
         * Handle data from the net on this local netMessenger.
         */
        // Don't handle loop-back messages.
        if (di.getMsgSender() === this.air.ourChannel) {
            return;
        }

        if (!this.__type2message.has(msgType)) {
            console.warn(`Received unknown message: ${msgType}`);
            return;
        }

        const message = this.__type2message.get(msgType)!;

        let sentArgs: any;
        try {
            sentArgs = decode(di.getBlob());
        } catch (err) {
            console.warn(`Failed to unpack msgpack for message ${message}:`, err);
            return;
        }

        if (!Array.isArray(sentArgs)) {
            console.warn(`Received non-list item in ${message} message:`, sentArgs);
            return;
        }

        void this.dispatch(message, sentArgs);
    }

    private async dispatch(message: string, args: any[]) {
        const listeners = this.__listeners.get(message);
        if (!listeners || listeners.size === 0) {
            return;
        }

        await Promise.all(
            [...listeners].map(async (callback) => {
                try {
                    await callback(...args);
                } catch (err) {
                    console.error(`Error in NetMessenger handler for ${message}:`, err);
                }
            }),
        );
    }
}
