name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: requirements_dev.txt

      - name: Installing
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt

      - name: Formatting
        run: python -m black . --check --exclude gens

      - name: Testing
        run: python -m unittest discover -v -s ./tests -p "test_*.py"
